-- Gap-filling plants generated by GapAnalyser
-- Run: 2026-07-16
-- Gaps found: 0 condition combos
-- Plants added: 36

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Globe Thistle', 'Echinops ritro', 'perennial', 'Striking spherical steel-blue flower heads on tall stems from July to September. Extremely drought-tolerant. Loved by bees.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'chalk,loam,sand', 'alkaline,neutral', 'free', 1300.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Globe Thistle' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Globe Thistle'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Sea Holly', 'Eryngium maritimum', 'perennial', 'Architectural plant with spiky silver-blue flowers and foliage. Native coastal species. Thrives in poor, dry soil.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H5', 'chalk,sand', 'alkaline,neutral', 'free', 1400.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Sea Holly' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Sea Holly'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Verbena', 'Verbena bonariensis', 'perennial', 'Tall airy stems topped with clusters of tiny purple flowers. Flowers from June to first frost. Self-seeds generously.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H4', 'chalk,loam,sand', 'alkaline,neutral', 'free', 1300.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Verbena' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Verbena'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Pinks', 'Dianthus', 'perennial', 'Compact fragrant flowers in shades of pink, red, and white. Cottage garden staple. Needs sharp drainage.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H5', 'chalk,loam,sand', 'alkaline,neutral', 'free', 1300.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Pinks' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Pinks'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Stonecrop', 'Sedum spectabile', 'perennial', 'Fleshy-leaved succulent with flat pink flower heads in autumn. Important late nectar source for butterflies. Extremely tough.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'chalk,loam,sand', 'alkaline,neutral', 'free', 1200.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Stonecrop' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Stonecrop'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Bearded Iris', 'Iris germanica', 'perennial', 'Flamboyant flowers in every colour from May to June. Rhizomes need baking in sun. Excellent for hot, dry borders.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'chalk,loam,sand', 'alkaline,neutral', 'free', 1400.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Bearded Iris' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Bearded Iris'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Marsh Marigold', 'Caltha palustris', 'perennial', 'Cheerful golden flowers in March-April. Native wildflower for pond margins, bog gardens, and damp ditches.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'clay,loam', 'acid,neutral', 'waterlogged,moist,impeded', 800.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Marsh Marigold' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Marsh Marigold'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Siberian Iris', 'Iris sibirica', 'perennial', 'Elegant blue or white flowers on grassy foliage in June. Thrives in heavy, damp clay where many plants fail.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'clay,loam', 'acid,neutral', 'moist,impeded,waterlogged', 1000.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Siberian Iris' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Siberian Iris'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Ligularia', 'Ligularia dentata', 'perennial', 'Bold architectural plant with large round leaves and orange daisy flowers. Needs consistently moist soil — wilts in drought.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'clay,loam', 'acid,neutral', 'moist,impeded,waterlogged', 800.0, 'partial_shade', 1, 1 FROM plants WHERE common_name = 'Ligularia' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Ligularia'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Meadowsweet', 'Filipendula ulmaria', 'perennial', 'Fragrant creamy-white flower plumes from June to September. Native wildflower for damp meadows and stream banks.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'clay,loam', 'acid,neutral', 'moist,impeded,waterlogged', 800.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Meadowsweet' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Meadowsweet'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Purple Loosestrife', 'Lythrum salicaria', 'perennial', 'Tall spikes of vivid magenta flowers from June to September. Superb for wet clay and pond margins. Loved by bees.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'clay,loam', 'neutral', 'moist,impeded,waterlogged', 1000.0, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Purple Loosestrife' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Purple Loosestrife'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Gorse', 'Ulex europaeus', 'shrub', 'Spiny evergreen native shrub with coconut-scented yellow flowers almost year-round. Thrives on the poorest, most acid soils.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'sand,loam', 'acid', 'free', 1200.0, 'full_sun', 1, 0 FROM plants WHERE common_name = 'Gorse' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Gorse'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Broom', 'Cytisus scoparius', 'shrub', 'Fast-growing deciduous shrub smothered in yellow pea flowers in May-June. Ideal for dry banks and sandy acid soils.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H6', 'sand,loam', 'acid', 'free', 1200.0, 'full_sun', 1, 0 FROM plants WHERE common_name = 'Broom' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Broom'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Pieris', 'Pieris japonica', 'shrub', 'Evergreen shrub with striking red new growth and cascading white bell flowers in spring. Must have acid soil.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H5', 'loam,sand', 'acid', 'moist,free', 1000.0, 'partial_shade', 0, 0 FROM plants WHERE common_name = 'Pieris' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Pieris'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Azalea', 'Rhododendron (Azalea)', 'shrub', 'Compact deciduous or evergreen shrub with vibrant spring flowers. Needs acid soil — grow in ericaceous compost if needed.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H5', 'loam,sand', 'acid', 'moist,free', 1000.0, 'partial_shade', 0, 0 FROM plants WHERE common_name = 'Azalea' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Azalea'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Bilberry', 'Vaccinium myrtillus', 'shrub', 'Low-growing native shrub producing small sweet berries in summer. Found on acid heaths and moors. Edible wild fruit.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'sand,loam,peat', 'acid', 'free,moist', 1000.0, 'partial_shade', 1, 0 FROM plants WHERE common_name = 'Bilberry' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Bilberry'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Silver Birch', 'Betula pendula', 'tree', 'Elegant native tree with white bark and golden autumn colour. Pioneer species — grows almost anywhere including poor soil.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'any', 'any', 'free,moist', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Silver Birch' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Silver Birch'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Rowan', 'Sorbus aucuparia', 'tree', 'Hardy native tree with white spring flowers and bright red autumn berries. Grows at higher altitudes than any other UK tree.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'any', 'acid,neutral', 'free,moist', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Rowan' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Rowan'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Hawthorn', 'Crataegus monogyna', 'tree', 'Tough native hedging and specimen tree. White May blossom, red autumn haws. Supports over 300 insect species.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'any', 'any', 'any', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Hawthorn' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Hawthorn'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Wild Rose', 'Rosa canina', 'shrub', 'Native dog rose with single pink flowers in June and red hips in autumn. Extremely hardy. Grows in hedgerows and woodland edges.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'any', 'any', 'free,moist', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Wild Rose' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Wild Rose'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Scots Pine', 'Pinus sylvestris', 'tree', 'Iconic native conifer with distinctive orange bark and blue-green needles. Thrives on poor acid soils in exposed conditions.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'sand,loam', 'acid,neutral', 'free', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Scots Pine' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Scots Pine'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Holly', 'Ilex aquifolium', 'tree', 'Evergreen native tree with glossy spiny leaves and red winter berries. Excellent for hedging. Very pollution-tolerant.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'any', 'any', 'free,moist', NULL, 'partial_shade', 1, 1 FROM plants WHERE common_name = 'Holly' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Holly'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Privet', 'Ligustrum ovalifolium', 'shrub', 'Classic semi-evergreen hedging plant. Fast-growing, tolerates heavy clipping, pollution, and most soils. White summer flowers.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H6', 'any', 'any', 'any', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Privet' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Privet'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Pyracantha', 'Pyracantha coccinea', 'shrub', 'Thorny evergreen wall shrub with white flowers and masses of orange-red berries. Brilliant for security hedging and wildlife.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H6', 'any', 'any', 'free,moist', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Pyracantha' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Pyracantha'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Cotoneaster', 'Cotoneaster horizontalis', 'shrub', 'Low-spreading evergreen with herringbone branches. Red autumn berries loved by birds. Grows on walls, banks, and poor ground.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H6', 'any', 'any', 'free,moist', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Cotoneaster' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Cotoneaster'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Mahonia', 'Mahonia aquifolium', 'shrub', 'Evergreen shrub with holly-like leaves and yellow winter flowers followed by blue berries. Tough and shade-tolerant.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H6', 'any', 'any', 'any', NULL, 'partial_shade', 1, 1 FROM plants WHERE common_name = 'Mahonia' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Mahonia'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Bog Rosemary', 'Andromeda polifolia', 'shrub', 'Dainty evergreen dwarf shrub with pink bell flowers. Native to peat bogs. Needs acid, permanently moist conditions.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'peat,loam', 'acid', 'moist,waterlogged,impeded', NULL, 'full_sun', 1, 0 FROM plants WHERE common_name = 'Bog Rosemary' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Bog Rosemary'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Ragged Robin', 'Silene flos-cuculi', 'perennial', 'Charming native wildflower with deeply-cut pink petals. Thrives in damp meadows and marshy ground.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'clay,loam,peat', 'acid,neutral', 'moist,impeded,waterlogged', NULL, 'full_sun', 1, 1 FROM plants WHERE common_name = 'Ragged Robin' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Ragged Robin'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Royal Fern', 'Osmunda regalis', 'perennial', 'Magnificent native fern reaching 1.5m tall. Needs permanently moist, acid soil. Stunning autumn colour. Slow to establish.', 0);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H7', 'loam,peat', 'acid', 'moist,waterlogged,impeded', NULL, 'partial_shade', 1, 0 FROM plants WHERE common_name = 'Royal Fern' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Royal Fern'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Prayer Plant', 'Maranta leuconeura', 'perennial', 'Tropical houseplant with beautifully patterned leaves that fold upward at night. Needs humidity and filtered water.', 1);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H1a', 'loam', 'acid,neutral', 'moist', NULL, 'partial_shade', 1, 0 FROM plants WHERE common_name = 'Prayer Plant' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Prayer Plant'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Tradescantia', 'Tradescantia zebrina', 'perennial', 'Fast-growing trailing plant with striking purple-and-silver striped leaves. Very easy to propagate from cuttings.', 1);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H1c', 'loam', 'neutral', 'moist,free', NULL, 'partial_shade', 1, 1 FROM plants WHERE common_name = 'Tradescantia' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Tradescantia'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Philodendron', 'Philodendron scandens', 'climber', 'Heart-shaped glossy leaves on trailing or climbing stems. Tolerates low light well. Classic easy-care houseplant.', 1);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H1b', 'loam', 'neutral', 'moist,free', NULL, 'partial_shade', 1, 1 FROM plants WHERE common_name = 'Philodendron' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Philodendron'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Dragon Tree', 'Dracaena marginata', 'tree', 'Architectural indoor tree with narrow sword-like leaves on bare cane stems. Very tolerant of neglect and low light.', 1);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H1b', 'loam,sand', 'neutral', 'free', NULL, 'partial_shade', 1, 1 FROM plants WHERE common_name = 'Dragon Tree' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Dragon Tree'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('African Violet', 'Saintpaulia', 'perennial', 'Compact flowering houseplant that blooms almost year-round in the right conditions. Sensitive to cold water on leaves.', 1);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H1a', 'loam', 'acid,neutral', 'moist', NULL, 'partial_shade', 1, 0 FROM plants WHERE common_name = 'African Violet' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'African Violet'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Nerve Plant', 'Fittonia albivenis', 'perennial', 'Low-growing tropical plant with intricately veined leaves in pink, red, or white. Needs high humidity — ideal for terrariums.', 1);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H1a', 'loam', 'neutral', 'moist', NULL, 'full_shade', 1, 1 FROM plants WHERE common_name = 'Nerve Plant' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Nerve Plant'));

INSERT OR IGNORE INTO plants (common_name, latin_name, plant_type, description, is_indoor) VALUES
('Peperomia', 'Peperomia obtusifolia', 'perennial', 'Compact succulent-like houseplant with thick glossy leaves. Low maintenance and tolerant of irregular watering.', 1);
INSERT OR IGNORE INTO plant_requirements (plant_id, min_hardiness, soil_types, soil_ph, drainage, min_sun_hours, sun_preference, pollution_tolerant, hard_water_tolerant) 
SELECT id, 'H1b', 'loam,sand', 'neutral', 'free,moist', NULL, 'partial_shade', 1, 1 FROM plants WHERE common_name = 'Peperomia' AND NOT EXISTS (SELECT 1 FROM plant_requirements WHERE plant_id = (SELECT id FROM plants WHERE common_name = 'Peperomia'));

